# Generated by Django 4.1.2 on 2022-10-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='web/about/')),
            ],
            options={
                'verbose_name': 'about',
                'verbose_name_plural': 'abouts',
                'db_table': 'web_about',
            },
        ),
    ]
