# Generated by Django 5.2.1 on 2025-05-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_issueclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='web/why/')),
            ],
            options={
                'verbose_name': 'why',
                'verbose_name_plural': 'why',
                'db_table': 'web_why',
            },
        ),
    ]
