# Generated by Django 5.2.1 on 2025-05-20 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_whyclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fr_classes', to='web.whyclass')),
            ],
            options={
                'verbose_name': 'fr',
                'verbose_name_plural': 'fr',
                'db_table': 'fr',
            },
        ),
    ]
