# Generated by Django 5.2.1 on 2025-05-21 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_frclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='NopClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nop_classes', to='web.frclass')),
            ],
            options={
                'verbose_name': 'nop',
                'verbose_name_plural': 'nop',
                'db_table': 'nop',
            },
        ),
    ]
